# Generated by Django 4.2.4 on 2023-08-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "username",
                    models.CharField(max_length=20, unique=True, verbose_name="사용자 계정"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="비밀번호")),
                (
                    "email",
                    models.EmailField(
                        max_length=50, unique=True, verbose_name="이메일 주소"
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="이름"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
