# Generated by Django 4.2.4 on 2023-08-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="email address"
            ),
        ),
    ]
